name: PR Agent for NUWM

on:
  pull_request:
    types: [ opened, edited, synchronize ]

jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    name: Run pr agent on every pull request
    steps:
      - name: pr-agent-nuwm
        uses: EzGrade/Pr-Agent-NUWM@main
        env:
          APP_ID: ${{ secrets.APP_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }}
          INSTALLATION_ID: ${{ secrets.INSTALLATION_ID }}
